spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_LOGIN}
    #postgres по дефолту
    password: ${DB_PASS}
    # твой пароль от дб при установке
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema : koilgram
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: koilgram
server:
  servlet:
    context-path: /koilgram
  port: ${PORT:8080}
  #Дефолтный порт не менять вр как
server-mail:
  password: ${MAIL_PASS}
  #Пароль от почты
  login: ${MAIL_LOGIN}
  #Логин от почты
  host: ${MAIL_HOST}
  #Для Gmail smtp.gmail.com
  port: ${MAIL_PORT}
  #Gmail 587
server-ui:
  #http://localhost:4200 по дефолту
  url : ${UI_URL}

